# Generated by Django 4.1.5 on 2023-01-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Robot',
        ),
    ]
